version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: python manage.py runserver 0.0.0.0:8000
        # command: tail -f /dev/null
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        environment:
            - DATABASE=postgres
            - SQL_HOST=db
            - SQL_PORT=5432
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=nioukamoulcupuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=nioukamoulcup

volumes:
    postgres_data: