# Generated by Django 2.1.9 on 2019-09-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171109_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kcupuserprofile',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_profile', 'Can view profile'),)},
        ),
    ]
