# Generated by Django 2.1.9 on 2019-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Groupe de discussion', max_length=200),
            preserve_default=False,
        ),
    ]
