# Generated by Django 2.1.9 on 2019-09-12 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_blueprint',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'message_blueprint')},
        ),
    ]
