# Generated by Django 2.1.9 on 2019-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20190912_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hotlinked_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hotlinked_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
