# Generated by Django 2.1.9 on 2019-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20190912_1647'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='wall_post_created_90f63e_idx'),
        ),
    ]
