# Generated by Django 2.1.9 on 2019-09-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20190917_1008'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-updated_at'], name='wall_post_updated_bef290_idx'),
        ),
    ]
