# Generated by Django 2.1.9 on 2019-09-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20190920_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['message_blueprint'], name='wall_post_message_9ae8be_idx'),
        ),
    ]
