# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 10:35
from __future__ import unicode_literals

import colorful.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_maj', models.DateTimeField(null=True)),
                ('nom', models.CharField(max_length=100)),
                ('sn_team_uuid', models.UUIDField()),
                ('maillot_svg', models.CharField(choices=[('jersey-plain2', 'uni'), ('jersey-stripes-v2', 'rayures verticales'), ('jersey-diag-half-white2.svg', 'moitié diagonale blanche'), ('jersey-scap2', 'scapulaire'), ('jersey-shoulders2', 'épaules'), ('jersey-halfdark2', 'moitié assombrie'), ('jersey-stripe-center2', 'bande centrale'), ('jersey-stripe-h-bicolor2', 'bande horizontale bicolore'), ('jersey-stripe-h2', 'bande horizontale unie')], default='jersey-plain2', max_length=50)),
                ('maillot_color_bg', colorful.fields.RGBColorField(default='#FFFFFF')),
                ('maillot_color_stroke', colorful.fields.RGBColorField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_maj', models.DateTimeField(null=True)),
                ('prenom', models.CharField(blank=True, max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('surnom', models.CharField(blank=True, max_length=50)),
                ('sn_person_uuid', models.UUIDField()),
                ('poste', models.CharField(choices=[('G', 'Gardien'), ('D', 'Défenseur'), ('M', 'Milieu'), ('A', 'Attaquant')], max_length=1, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joueurs', to='ligue1.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_maj', models.DateTimeField(null=True)),
                ('numero', models.PositiveIntegerField()),
                ('sn_step_uuid', models.UUIDField()),
                ('debut', models.DateTimeField(null=True)),
                ('fin', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['saison', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_jeu', models.PositiveSmallIntegerField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligue1.Club')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='ligue1.Joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_maj', models.DateTimeField(null=True)),
                ('sn_meeting_uuid', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('resultat', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('club_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoit', to='ligue1.Club')),
                ('club_exterieur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite', to='ligue1.Club')),
                ('journee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencontres', to='ligue1.Journee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_maj', models.DateTimeField(null=True)),
                ('nom', models.CharField(max_length=100)),
                ('sn_instance_uuid', models.UUIDField()),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaisonCourante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_courante', to='ligue1.Saison')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='ligue1.Rencontre'),
        ),
        migrations.AddField(
            model_name='journee',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journees', to='ligue1.Saison'),
        ),
        migrations.AddField(
            model_name='club',
            name='participations',
            field=models.ManyToManyField(related_name='participants', to='ligue1.Saison'),
        ),
    ]
