# Generated by Django 2.0.6 on 2018-06-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligue1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='ligue1.Club'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligue1.Club'),
        ),
        migrations.AlterField(
            model_name='rencontre',
            name='club_domicile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoit', to='ligue1.Club'),
        ),
        migrations.AlterField(
            model_name='rencontre',
            name='club_exterieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visite', to='ligue1.Club'),
        ),
    ]
