# Generated by Django 2.0.6 on 2018-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligue1', '0002_auto_20180628_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='journee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
