# Generated by Django 2.0.6 on 2018-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligue1', '0003_journee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='maillot_svg',
            field=models.CharField(choices=[('jersey-plain2', 'uni'), ('jersey-stripes-v2', 'rayures verticales'), ('jersey-sleeves2', 'manches'), ('jersey-diag-half-white2.svg', 'moitié diagonale blanche'), ('jersey-scap2', 'scapulaire'), ('jersey-shoulders2', 'épaules'), ('jersey-halfdark2', 'moitié assombrie'), ('jersey-stripe-center2', 'bande centrale'), ('jersey-stripe-h-bicolor2', 'bande horizontale bicolore'), ('jersey-stripe-h2', 'bande horizontale unie')], default='jersey-plain2', max_length=50),
        ),
    ]
