# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merkatosession',
            name='result',
        ),
        migrations.AddField(
            model_name='auction',
            name='is_valid',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='auction',
            name='reject_cause',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merkatosession',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='winning_auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_won', to='game.Auction'),
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together=set([('sale', 'team')]),
        ),
    ]
