# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligue1', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jjscore',
            name='rencontre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligue1.Rencontre'),
        ),
    ]
