# Generated by Django 2.0.6 on 2018-06-28 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligue1', '0002_auto_20180628_1552'),
        ('game', '0002_jjscore_rencontre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SJScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('avg_note', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('nb_notes', models.PositiveIntegerField(default=0)),
                ('total_bonuses', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('sum_compensations', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligue1.Joueur')),
                ('saison_scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.SaisonScoring')),
            ],
        ),
        migrations.AlterField(
            model_name='leaguedivision',
            name='lower_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper', to='game.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='leaguedivision',
            name='upper_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lower', to='game.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='winning_auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_won', to='game.Auction'),
        ),
    ]
