# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170704_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=set([('merkato_session', 'rank')]),
        ),
    ]
