# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170706_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('merkato_session', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=set([('merkato_session', 'rank'), ('merkato_session', 'player')]),
        ),
    ]
