# Generated by Django 2.0.6 on 2018-09-17 21:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180628_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemembership',
            name='is_team_captain',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaguemembership',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaguemembership',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.League'),
        ),
    ]
