# Generated by Django 2.0.6 on 2018-08-30 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180628_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='league_instance',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='game.LeagueInstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merkato',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
