# Generated by Django 2.0.6 on 2018-09-17 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20180917_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueInvitation',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=8)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.League')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=8)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
