# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_bankaccount_bankaccounthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounthistory',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.BankAccount'),
        ),
    ]
