# Generated by Django 2.0.6 on 2018-09-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180830_1159'),
        ('game', '0005_leagueinvitation_teaminvitation'),
    ]

    operations = [
    ]
