# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170708_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4)),
                ('done', models.BooleanField(default=False)),
                ('merkato_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MerkatoSession')),
            ],
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='adjust',
            new_name='blocked',
        ),
        migrations.RemoveField(
            model_name='signing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='signing',
            name='is_current',
        ),
        migrations.AddField(
            model_name='signing',
            name='begin',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signing',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='signing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Signing'),
        ),
    ]
