# Generated by Django 2.0.6 on 2018-09-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20180918_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueinvitation',
            name='status',
            field=models.CharField(choices=[('OPENED', 'OPENED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED')], default='OPENED', max_length=8),
        ),
        migrations.AlterField(
            model_name='leagueinvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.League'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('OPENED', 'OPENED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CLOSED', 'CLOSED')], default='OPENED', max_length=8),
        ),
    ]
