# Generated by Django 2.0.6 on 2018-09-27 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180927_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
