# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 20:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170710_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='merkatosession',
            name='solving',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 20, 49, 24, 515476, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
