# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 21:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_merkatosession_solving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merkatosession',
            options={'ordering': ('closing',)},
        ),
        migrations.AddField(
            model_name='teamdayscore',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'notes': [('HALFSEASON', 13), ('FULLSEASON', 26), ('TOURNAMENT', 3)]}),
        ),
        migrations.AlterField(
            model_name='leagueinstancephase',
            name='type',
            field=models.CharField(choices=[('HALFSEASON', 'Half season'), ('FULLSEASON', 'Whole season'), ('TOURNAMENT', 'Tournament')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leagueinstancephaseday',
            name='results',
            field=models.ManyToManyField(null=True, through='game.TeamDayScore', to='game.Team'),
        ),
        migrations.AlterField(
            model_name='signing',
            name='begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signing',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='leagueinstancephase',
            unique_together=set([('league_instance', 'journee_first'), ('league_instance', 'journee_last')]),
        ),
    ]
