# Generated by Django 2.0.6 on 2018-10-22 11:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20181008_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftsessionrank',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='merkato',
            name='last_solving',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='draftsession',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
