# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170719_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"notes": {"TOURNAMENT": 3, "HALFSEASON": 13, "FULLSEASON": 26}}'),
        ),
        migrations.AlterField(
            model_name='signing',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"score_factor": 1.0}'),
        ),
    ]
