# Generated by Django 2.0.6 on 2018-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20181022_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdayscore',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merkato',
            name='last_solving',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
