# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170719_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"notes": {"FULLSEASON": 26, "HALFSEASON": 13, "TOURNAMENT": 3}}'),
        ),
        migrations.AlterField(
            model_name='leagueinstancephase',
            name='journee_first',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leagueinstancephase',
            name='journee_last',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leagueinstancephaseday',
            name='results',
            field=models.ManyToManyField(through='game.TeamDayScore', to='game.Team'),
        ),
        migrations.AlterField(
            model_name='signing',
            name='begin',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='signing',
            name='end',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
