# Generated by Django 2.0.6 on 2018-11-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20181108_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccounthistory',
            options={'ordering': ('-date', 'new_balance')},
        ),
    ]
