# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170721_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"notes": {"FULLSEASON": 26, "TOURNAMENT": 3, "HALFSEASON": 13}}'),
        ),
    ]
