# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 14:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20170731_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueinstancephaseday',
            options={'ordering': ['journee']},
        ),
        migrations.AlterModelOptions(
            name='teamdayscore',
            options={'ordering': ['-day']},
        ),
        migrations.AddField(
            model_name='jjscore',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'notes': {'FULLSEASON': 26, 'HALFSEASON': 13, 'TOURNAMENT': 3}}),
        ),
        migrations.AlterField(
            model_name='signing',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'score_factor': 1.0}),
        ),
    ]
