# Generated by Django 2.0.6 on 2018-12-10 16:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20181108_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing', models.DateTimeField()),
                ('is_solved', models.BooleanField(default=False)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('merkato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Merkato')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionTeamChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_to_choose', django.contrib.postgres.fields.jsonb.JSONField()),
                ('signings_to_free', models.ManyToManyField(to='game.Signing')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Team')),
                ('transition_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.TransitionSession')),
            ],
        ),
    ]
