# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 16:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20171109_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='merkatosession',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
