# Generated by Django 2.0.6 on 2019-02-07 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_transitionsession_transitionteamchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueinstancephase',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='merkato',
            name='mode',
            field=models.CharField(choices=[('DRFT', 'Draft'), ('BID', 'Bid'), ('TRS', 'Transition')], max_length=4),
        ),
    ]
