# Generated by Django 2.0.6 on 2019-03-12 14:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20190308_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='palmares',
            name='players_ranking',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
