# Generated by Django 2.0.6 on 2019-04-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_palmares_players_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='palmares',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.League'),
        ),
    ]
