# Generated by Django 2.0.6 on 2019-04-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_palmares_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampalmaresranking',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.LeagueDivision'),
        ),
    ]
