# Generated by Django 2.1.9 on 2019-09-13 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import game.models.league_models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20190912_1647'),
        ('game', '0020_teampalmaresranking_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='wall_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wall.Group'),
        ),
        migrations.AlterField(
            model_name='jjscore',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='leagueinstance',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=game.models.league_models.default_leagueinstance_configuration),
        ),
        migrations.AlterField(
            model_name='signing',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=game.models.league_models.default_signing_attributes),
        ),
        migrations.AlterField(
            model_name='sjscore',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.League'),
        ),
    ]
