# Generated by Django 2.1.9 on 2020-02-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20190913_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('PLAY', 'En jeu'), ('EXCL', 'Exclu'), ('DISM', 'Abandon')], default='PLAY', max_length=4),
        ),
    ]
