# Generated by Django 2.1.9 on 2021-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signing',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
